### ISSUE TITLE
JSON: null value causes invalid memory address or nil pointer dereference error

### ISSUE THREAD

**Issue by mcapodici** [cube2222/octosql#113]
Platform: Windows

example.json:
```
[{
  "nameCache": null
}]
```

settings.yaml
```
dataSources:
  - name: t
    type: json
    config:
      path: "example.json"
      arrayFormat: true
```

command
`octosql "select * from t as tt" -c settings.yaml`

result:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xf8 pc=0x51bce6]

goroutine 1 [running]:
github.com/cube2222/octosql.NormalizeType(0x0, 0x0, 0xc00009b988, 0x2)
        /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/values.go:235 +0xbb6
github.com/cube2222/octosql/storage/json.(*RecordStream).Next(0xc0001064b0, 0xc000079e60, 0x9c9e20, 0xc0001064b0)
        /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/storage/json/datasource.go:120 +0x32d
github.com/cube2222/octosql/app.(*App).RunPlan(0xc00009bd18, 0x9cf420, 0xc0000700b0, 0x9c4740, 0xc0000de460, 0x0, 0xc00009bd38)
        /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/app/app.go:45 +0x1a3
main.glob..func1(0xd31520, 0xc000079aa0, 0x1, 0x3)
        /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/cmd/octosql/main.go:94 +0x594
github.com/spf13/cobra.(*Command).execute(0xd31520, 0xc00006c0d0, 0x3, 0x3, 0xd31520, 0xc00006c0d0)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2b5
github.com/spf13/cobra.(*Command).ExecuteC(0xd31520, 0xd36a90, 0x924ae8, 0x6)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x303
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/cmd/octosql/main.go:105 +0x157
```

**Comment by cube2222** [comment]
Hey, thanks for the issue report! The fix is now on the master branch. We'll do a point release by the end of the week. If you want the fix asap though, you can download the binaries from the CI build: https://circleci.com/gh/cube2222/octosql/1485#artifacts/containers/0

**Comment by cube2222** [comment]
The coalesce and nullif functions have been added for working with null values.

**Comment by martin-displayr** [comment]
Great, thank you that's a very quick turnaround.
